version: '3.9'
services:
  app:
    container_name: go-app
    image: heepoke/go-app:latest
    build: .
    environment:
      DATABASE_URL: "host=mysql-db user=root password= dbname=goapi sslmode=disable"
    ports:
      - "6476:6476"
    depends_on:
      - db
    networks:
      - app_network
  db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: goapi
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - app_network
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
  jenkins_home: