version: '3.9'
services:
  go-app:
    container_name: go-app
    image: heepoke/go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=mysql-db user=root password= dbname=goapi sslmode=disable"
    ports:
      - "6476:6476"
    depends_on:
      - db
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: goapi
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    restart: always
    networks:
      - backend
networks:
  backend:
    driver: bridge

